"""rename OrderRequest model to Order

Revision ID: 3cccd0a78304
Revises: 2fd3c5ca2f23
Create Date: 2026-01-21 02:28:38.940510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3cccd0a78304'
down_revision = '2fd3c5ca2f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('order_request')
    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('bid_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'order', ['request_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('bid_ibfk_1'), 'order_request', ['request_id'], ['id'])

    op.create_table('order_request',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('buyer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer_profile.id'], name=op.f('order_request_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('order')
    # ### end Alembic commands ###
